
name: Deploy to WordPress.org

on:
  push:
    tags:
    - "v*"

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Subversion
      run: sudo apt-get update && sudo apt-get install -y subversion

    - name: Validate Tag Format and Sync Version
      id: validate_tag
      run: |
        TAG_VERSION="${GITHUB_REF_NAME#v}"
        PLUGIN_VERSION=$(grep -Po "(?<=Version: )[\d.]+" wp-sms.php)
        
        if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "❌ Invalid tag format: ${GITHUB_REF_NAME}. Must match 'vX.X.X'."
          exit 1
        fi
        
        if [[ "${TAG_VERSION}" != "${PLUGIN_VERSION}" ]]; then
          echo "❌ Tag version (${TAG_VERSION}) does not match plugin version (${PLUGIN_VERSION})."
          exit 1
        fi
        
        echo "✅ Tag and plugin version validated successfully."

    - name: Update readme.txt Version
      run: |
        sed -i "s/^Stable tag: .*/Stable tag: ${GITHUB_REF_NAME#v}/" readme.txt
        echo "✅ Updated readme.txt with version ${GITHUB_REF_NAME#v}."

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wp-sms

    - name: Notify Slack
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "🚀 Deploy completed successfully for wp-sms (${GITHUB_REF_NAME})."
        }' ${{ secrets.SLACK_WEBHOOK }}

    - name: Deployment Summary
      run: |
        echo "✅ Deploy to WordPress.org completed successfully for tag ${GITHUB_REF_NAME}."
