
name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Python (for logging and advanced handling)
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: AI Code Reviewer
        id: ai_review
        uses: veronalabs/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4-turbo"
          exclude: |
            tests/,
            vendor/,
            assets/,
            languages/,
            composer.lock,
            CHANGELOG.md,
            readme.txt

      - name: Post Review Summary
        if: steps.ai_review.outputs.review-status == 'completed'
        run: |
          echo "AI Code Review Completed. Check Pull Request Comments for Details."
